image: node:18.13.0-alpine

stages:
  - build
  - test
  - sonarqube
  - sonarqube-vulnerability-report
build-job:
  stage: build
  tags:
    - shared
  before_script:
    - cd prototype/prioss
    - npm ci
  script:
    - npm run build

lint-job:
  stage: test
  tags:
    - shared
  before_script:
    - cd prototype/prioss
    - npm ci
  script:
    - npm run lint

sonarqube-check:
  stage: sonarqube
  tags:
    - shared
  dependencies:
    - get-binaries
    - build
  cache:
    policy: pull
    key: "${CI_COMMIT_SHORT_SHA}"
    paths:
      - sonar-scanner/
  script: 
    - sonar-scanner
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'

sonarqube-vulnerability-report:
  stage: sonarqube-vulnerability-report
  tags:
    - shared
  script:
    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/issues/gitlab_sast_export?projectKey=ekablo_prioss_9834f000-aa16-42c2-9ade-bcf1945b0cca&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'dev'
  artifacts:
    expire_in: 1 day
    reports:
      sast: gl-sast-sonar-report.json
