image: node:latest

stages:
  - build
  - test

build-job:
  stage: build
  before_script:
    - cd prototype/prioss
    - npm ci
  script:
    - npm run build

lint-job:
  stage: test
  before_script:
    - cd prototype/prioss
    - npm ci
  script:
    - npm run lint