// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
/**
 * @example 
 * {
  "other_photos_v2": [
    {
      "uri": "your_activity_across_facebook/posts/media/your_posts/993447_640074476036848_1585615850_n_640074476036848.jpg",
      "creation_timestamp": 1383047266,
      "media_metadata": {
        "photo_metadata": {
          "exif_data": [
            {
              "upload_ip": "109.42.3.161",
              "taken_timestamp": 1383047269
            }
          ]
        }
      }
    }]
    }
 */

export interface UncategorizedPhotos {
    other_photos_v2: OtherPhotosV2[];
}

export interface OtherPhotosV2 {
    uri: string;
    creation_timestamp: number;
    media_metadata: MediaMetadata;
}

export interface MediaMetadata {
    photo_metadata: PhotoMetadata;
}

export interface PhotoMetadata {
    exif_data: ExifDatum[];
}

export interface ExifDatum {
    upload_ip: string;
    taken_timestamp: number;
}